In [3]:
import pandas as pd
import os
import openpyxl

In [20]:
df = pd.read_excel("/CaiL/makeVoc/고장 VOC 세부내역 예시_보안해제본.xlsx")
df.head(2)

,Unnamed: 0,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,...,Unnamed: 48,Unnamed: 49,Unnamed: 50,Unnamed: 51,Unnamed: 52,Unnamed: 53,Unnamed: 54,Unnamed: 55,Unnamed: 56,Unnamed: 57
0,NaN,TT번호,접수시각,발생/해제,본부,지사,국사,사업장,서비스,상품명,...,회복시간,모뎀제조사,모뎀모델,AP제조사,AP모델,셋탑제조사(SA),셋탑모델(SA),접수번호,접수유형,VoIP단말모델
1,NaN,2023061400021568,2023-06-14 09:59:05,해제,동부고객본부,강릉지사,강릉국사,입암주공2차,TV,TV,...,2023-06-14 09:59:05,NaN,NaN,NaN,NaN,가온미디어,KAO_NA1100,SR20230614095712-1-1Q7UOZ2F,일반SR,NaN

In [21]:
col = df.loc[0]
df.columns=col
df = df[1:]

In [22]:
col=["접수시각","회선명","상세주소","연락처1","서비스","발생/해제"]
df = df[col]
df['manager_id'] = 0
for i in range(1,17):
    df.loc[i,'manager_id'] = int(i%5+1)
df['status_detail']="temp"
df = df.reset_index()
df.columns=["voc_id","date","name","customer_address","customer_phone","type","status","manager_id","status_detail"]

In [23]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 16 entries, 0 to 15
Data columns (total 9 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   voc_id            16 non-null     int64
 1   date              16 non-null     object
 2   name              16 non-null     object
 3   customer_address  16 non-null     object
 4   customer_phone    16 non-null     object
 5   type              16 non-null     object
 6   status            16 non-null     object
 7   manager_id        16 non-null     int64
 8   status_detail     16 non-null     object
dtypes: int64(2), object(7)
memory usage: 1.2+ KB

In [24]:
df.to_csv("testVoc.csv", index=False)

In [25]:
pd.read_csv("testVoc.csv")

,voc_id,date,name,customer_address,customer_phone,type,status,manager_id,status_detail
0,1,2023-06-14 09:59:05,김정*,강원도 강릉시 입암동 **********,010-67**-*860,TV,해제,2,temp
1,2,2023-06-14 07:44:19,이기*,강원도 강릉시 입암동 **********,010-40**-*802,인터넷,발생,3,temp
2,3,2023-06-14 10:38:04,최영*,강원도 강릉시 송정동 ******,010-24**-*105,TV,해제,4,temp
3,4,2023-06-14 07:54:53,박미*,강원도 강릉시 입암동 **********,010-77**-*277,TV,발생,5,temp
4,5,2023-06-14 07:36:53,최금*,강원도 강릉시 입암동 **********,010-55**-*554,TV,발생,1,temp
5,6,2023-06-14 08:03:14,정정*,강원도 강릉시 입암동 **********,010-27**-*034,TV,해제,2,temp
6,7,2023-06-14 09:06:28,이재*,강원도 강릉시 입암동 **********,010-52**-*488,TV,해제,3,temp
7,8,2023-06-14 07:50:55,이성*,강원도 강릉시 입암동 **********,010-87**-*235,인터넷,발생,4,temp
8,9,2023-06-14 11:13:00,서진*,강원도 강릉시 포남동 **********,010-94**-*031,TV,발생,5,temp
9,10,2023-06-14 09:34:25,곽용*,강원도 강릉시 입암동 **********,010-63**-*318,TV,해제,1,temp
10,11,2023-06-14 09:02:04,김옥*,강원도 강릉시 입암동 **********,010-74**-*315,TV,발생,2,temp
11,12,2023-06-14 08:26:26,고기*,강원도 강릉시 입암동 **********,010-56**-*788,TV,발생,3,temp
12,13,2023-06-14 08:13:16,김창*,강원도 강릉시 입암동 **********,010-99**-*111,인터넷,해제,4,temp
13,14,2023-06-14 09:42:43,오흥*,강원도 강릉시 입암동 *****,010-53**-*252,TV,해제,5,temp
14,15,2023-06-14 09:44:41,최호*,강원도 강릉시 포남동 **********,010-54**-*288,TV,발생,1,temp
15,16,2023-06-14 10:09:56,KT강원본*,강원도 강릉시 입암동 **********,010-96**-*868,인터넷,해제,2,temp